### ISSUE TITLE
[BUG] [Mac OS] Application Crashes on Sequoia 15.2

### ISSUE THREAD

**Issue by leetskeet** [streetpea/chiaki-ng#515]
**Describe the bug**
chiaki-ng 1.9.3 fails to start on Intel Macbook Pro running Sequoia 15.2

**Debug Log**
Attached

**To Reproduce**
1. Run on Sequoia 15.2
2. Open application.

**Expected behavior**
Application runs

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Mac OS Intel
 - Version 15.2
 - Device Macbook Pro
 - chiaki-ng Version 1.93

[chiaki-crash-26.12.2024.txt](https://github.com/user-attachments/files/18256294/chiaki-crash-26.12.2024.txt)
<img width="277" alt="Screenshot 2024-12-26 at 7 20 10 PM" src="https://github.com/user-attachments/assets/0fba45e9-3267-4a36-812c-bcd82cd216b7" />

**Comment by streetpea** [comment]
Does this work for you: https://github.com/streetpea/chiaki-ng/actions/runs/12509876263/artifacts/2364582074?

**Comment by leetskeet** [comment]
That version worked for me, thank you for all you do!

**Comment by streetpea** [comment]
@leetskeet does the version on the releases page still not work for you though?

**Comment by leetskeet** [comment]
The version installed via Homebrew does not work and the 1.9.3 Latest/non-weekly release downloaded directly does not work. Both give the same error as originally submitted.

**Comment by streetpea** [comment]
@leetskeet it looks like things get messed up on my dev instance that I use to make the x86 version so that it's compatible with MacOS 12+ since a lot of people with Intel Macs have older MacOS versions. I'll run some brew upgrades and then post a new version that should fix the issue.

**Comment by leetskeet** [comment]
@streetpea Just to clarify, my Intel Mac is on the latest, 15.2.

It was working on Mac OS 15.1, but it broke after updating to 15.2.

**Comment by streetpea** [comment]
@leetskeet it looks like there was a packaging issue so the path for one library got messed up so instead of using the bundled one it was requiring for you to have it installed on your system and since it wasn't it couldn't run. It should be fixed now. I uploaded a new version of the 1.9.3 release that should have the correct packaging. Thanks for bringing it to my attention. Please test it to verify.

**Comment by leetskeet** [comment]
Unfortunately still seeing it crash from Homebrew install and direct download, error log attached
[chiaki-ng_crash.txt](https://github.com/user-attachments/files/18267515/chiaki-ng_crash.txt)

**Comment by streetpea** [comment]
@leetskeet okay so the original issue was fixed but another package had the same issue. Before I just updated that package.I'll update all of my packages which should fix it.

**Comment by streetpea** [comment]
@leetskeet I've updated all packages and now created a new build and replaced the 1.9.3 build with it. Can you test this build?

**Comment by leetskeet** [comment]
Working now! Thank you.

**Comment by dankreiner** [comment]
Hey There, Im on Intel Mac, sequoia 15.3.1 and none of them are working for me unfortunately.
